"""Call only the three fixed PostgreSQL functions for the ADTOF smoke client.

This module is a source-only adapter over injected DB-API-like connection
objects. It imports no Psycopg, opens no network connection itself, and exposes
no generic SQL or table capability. A later composition root may create a
restricted Psycopg connection from the fixed smoke settings, then pass a
zero-argument factory here.

The adapter never selects from ``jobs``, ``outbox_events``, or
``processing_tasks``. Its SQL names only the administrator-owned
``prepare``/``observe``/successful-only ``cleanup`` functions created by the
already-applied smoke database bootstrap Job.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Mapping
from contextlib import suppress
from typing import Protocol
from uuid import UUID

from adtof_worker_smoke_contract import (
    CLEANUP_FUNCTION,
    OBSERVE_FUNCTION,
    PREPARE_FUNCTION,
    ADTOFWorkerSmokeContractError,
    ADTOFWorkerSmokeDatabase,
    ADTOFWorkerSmokeObservation,
    PreparedADTOFWorkerSmoke,
)


# Every query is fixed source text. Parameters are passed separately to the
# driver, so generated byte evidence cannot change the selected function or
# become a table name, object key, identifier, or SQL fragment.
PREPARE_FIXED_EVENT_SQL = f"""
    SELECT smoke_job_id::text AS smoke_job_id, smoke_event_id::text AS smoke_event_id
    FROM {PREPARE_FUNCTION}(%s, %s)
"""
OBSERVE_FIXED_EVENT_SQL = f"SELECT * FROM {OBSERVE_FUNCTION}()"
CLEANUP_FIXED_SUCCESS_SQL = f"SELECT {CLEANUP_FUNCTION}() AS cleaned"

_PREPARE_RESULT_COLUMNS = frozenset({"smoke_job_id", "smoke_event_id"})
_OBSERVATION_RESULT_COLUMNS = frozenset(
    {
        "publication_status",
        "published_at",
        "task_id",
        "task_status",
        "task_attempt_count",
        "task_lease_is_clear",
        "task_completed_at",
        "job_status",
    }
)
_CLEANUP_RESULT_COLUMNS = frozenset({"cleaned"})
_SHA256_PATTERN = re.compile(r"[0-9a-f]{64}")
_MAX_STEM_BYTES = 1 * 1024 * 1024


class ADTOFWorkerSmokeDatabaseInfrastructureError(RuntimeError):
    """Hide driver/network diagnostics that could disclose local DB details."""


class ADTOFWorkerSmokeDatabaseProtocolError(RuntimeError):
    """Reject an unexpected database row before a client can trust or clean it."""


class ADTOFWorkerSmokeDatabaseCursor(Protocol):
    """The tiny parameterized cursor surface used by the three fixed functions."""

    def execute(self, query: str, params: tuple[object, ...] = ()) -> object:
        """Execute source-controlled SQL with separately bound evidence values."""

    def fetchone(self) -> Mapping[str, object] | None:
        """Return one dictionary-shaped function row, if the function produced one."""

    def __enter__(self) -> "ADTOFWorkerSmokeDatabaseCursor":
        """Enter a driver-provided cursor scope."""

    def __exit__(self, *arguments: object) -> object:
        """Release the cursor scope without becoming an application transaction API."""


class ADTOFWorkerSmokeDatabaseConnection(Protocol):
    """The minimal connection lifecycle needed by this fixed-function adapter."""

    def cursor(self) -> ADTOFWorkerSmokeDatabaseCursor:
        """Return a dictionary-row cursor supplied by a later connection factory."""

    def commit(self) -> object:
        """Commit only a successful durable prepare or cleanup mutation."""

    def rollback(self) -> object:
        """Discard an invalid mutation or finish an observe-only transaction."""

    def close(self) -> object:
        """Release the restricted connection after each short function call."""


def _validated_stem_evidence(*, stem_size_bytes: object, stem_sha256: object) -> tuple[int, str]:
    """Repeat bounded fixture evidence validation before it reaches the database driver."""

    if (
        type(stem_size_bytes) is not int
        or not 1 <= stem_size_bytes <= _MAX_STEM_BYTES
        or not isinstance(stem_sha256, str)
        or _SHA256_PATTERN.fullmatch(stem_sha256) is None
    ):
        raise ADTOFWorkerSmokeContractError("Controlled smoke WAV evidence is invalid.")
    return stem_size_bytes, stem_sha256


def _exact_mapping(
    row: object, *, expected_columns: frozenset[str], operation: str
) -> Mapping[str, object]:
    """Require one exact safe projection instead of accepting arbitrary DB fields."""

    if not isinstance(row, Mapping) or set(row) != expected_columns:
        raise ADTOFWorkerSmokeDatabaseProtocolError(
            f"Smoke database {operation} result is invalid."
        )
    return row


def _observation_task_id(value: object) -> str | None:
    """Normalize Psycopg's native UUID only at the fixed observer boundary.

    PostgreSQL returns the `task_id` column as a native :class:`uuid.UUID` when
    Psycopg uses its default UUID adapter.  The smoke contract deliberately
    stores canonical strings so it is transport-neutral and can validate the
    exact textual representation before later MinIO verification.  Convert
    only that expected database-native value; arbitrary objects are rejected
    rather than being stringified into a value that might appear valid.
    """

    if value is None or isinstance(value, str):
        return value
    if isinstance(value, UUID):
        return str(value)
    raise ADTOFWorkerSmokeDatabaseProtocolError("Smoke database observation task ID is invalid.")


def _rollback_safely(connection: ADTOFWorkerSmokeDatabaseConnection) -> None:
    """Best-effort cleanup never replaces the original bounded error category."""

    with suppress(Exception):
        connection.rollback()


def _close_safely(connection: ADTOFWorkerSmokeDatabaseConnection) -> None:
    """Always release a short-lived restricted connection without exposing an error."""

    with suppress(Exception):
        connection.close()


class FixedFunctionADTOFWorkerSmokeDatabaseAdapter(ADTOFWorkerSmokeDatabase):
    """Run only prepare, observe, and successful cleanup against one fixed test.

    The adapter opens one short transaction per method through the injected
    factory. It never encloses MinIO I/O, a model process, RabbitMQ work, or a
    polling loop in a database transaction. Direct use of this class cannot
    select other Jobs, mutate a caller-chosen row, or run caller-selected SQL.
    """

    def __init__(
        self, connection_factory: Callable[[], ADTOFWorkerSmokeDatabaseConnection]
    ) -> None:
        """Store a connection factory without invoking it or connecting during construction."""

        if not callable(connection_factory):
            raise TypeError("connection_factory must be callable.")
        self._connection_factory = connection_factory

    def _open_connection(self) -> ADTOFWorkerSmokeDatabaseConnection:
        """Create one restricted connection while hiding concrete driver failures."""

        try:
            connection = self._connection_factory()
        except Exception as error:
            raise ADTOFWorkerSmokeDatabaseInfrastructureError(
                "Smoke database connection is unavailable."
            ) from error
        for required_method in ("cursor", "commit", "rollback", "close"):
            if not hasattr(connection, required_method):
                _close_safely(connection)
                raise ADTOFWorkerSmokeDatabaseProtocolError("Smoke database connection is invalid.")
        return connection

    def prepare_fixed_event(
        self, *, stem_size_bytes: int, stem_sha256: str
    ) -> PreparedADTOFWorkerSmoke:
        """Create exactly the reserved Job/outbox event after MinIO input proof.

        The PostgreSQL security-definer function performs the authoritative
        all-or-nothing Job/event insert. This adapter commits only after it has
        received and validated the exact fixed row; any driver/result failure
        rolls back instead of leaving a half-trusted client result.
        """

        size_bytes, sha256 = _validated_stem_evidence(
            stem_size_bytes=stem_size_bytes,
            stem_sha256=stem_sha256,
        )
        connection = self._open_connection()
        try:
            with connection.cursor() as cursor:
                cursor.execute(PREPARE_FIXED_EVENT_SQL, (size_bytes, sha256))
                row = _exact_mapping(
                    cursor.fetchone(),
                    expected_columns=_PREPARE_RESULT_COLUMNS,
                    operation="prepare",
                )
            prepared = PreparedADTOFWorkerSmoke(
                job_id=row["smoke_job_id"],
                event_id=row["smoke_event_id"],
            )
            connection.commit()
            return prepared
        except (ADTOFWorkerSmokeContractError, ADTOFWorkerSmokeDatabaseProtocolError):
            _rollback_safely(connection)
            raise
        except Exception as error:
            _rollback_safely(connection)
            raise ADTOFWorkerSmokeDatabaseInfrastructureError(
                "Smoke database prepare is unavailable."
            ) from error
        finally:
            _close_safely(connection)

    def observe_fixed_event(self) -> ADTOFWorkerSmokeObservation | None:
        """Read only the compact fixed-coordinate function projection.

        A read-only PostgreSQL `SELECT` can still open a transaction in common
        drivers. This method explicitly rolls it back after reading so a future
        polling loop never accumulates idle snapshots or holds a transaction.
        """

        connection = self._open_connection()
        try:
            with connection.cursor() as cursor:
                cursor.execute(OBSERVE_FIXED_EVENT_SQL)
                raw_row = cursor.fetchone()
            if raw_row is None:
                result: ADTOFWorkerSmokeObservation | None = None
            else:
                row = _exact_mapping(
                    raw_row,
                    expected_columns=_OBSERVATION_RESULT_COLUMNS,
                    operation="observe",
                )
                result = ADTOFWorkerSmokeObservation(
                    publication_status=row["publication_status"],
                    published_at=row["published_at"],
                    # The SQL function returns a PostgreSQL UUID. Psycopg
                    # correctly decodes it to ``UUID`` instead of ``str``;
                    # normalize that one approved driver representation before
                    # the strict smoke contract validates its canonical text.
                    task_id=_observation_task_id(row["task_id"]),
                    task_status=row["task_status"],
                    task_attempt_count=row["task_attempt_count"],
                    task_lease_is_clear=row["task_lease_is_clear"],
                    task_completed_at=row["task_completed_at"],
                    job_status=row["job_status"],
                )
            connection.rollback()
            return result
        except (ADTOFWorkerSmokeContractError, ADTOFWorkerSmokeDatabaseProtocolError):
            _rollback_safely(connection)
            raise
        except Exception as error:
            _rollback_safely(connection)
            raise ADTOFWorkerSmokeDatabaseInfrastructureError(
                "Smoke database observation is unavailable."
            ) from error
        finally:
            _close_safely(connection)

    def cleanup_fixed_success(self) -> bool:
        """Call the fixed successful-only cleanup function and commit only deletion.

        ``False`` means PostgreSQL retained evidence because the full success
        predicate was not true. The adapter rolls that read-only/no-delete path
        back rather than claiming cleanup occurred or committing a later change.
        """

        connection = self._open_connection()
        try:
            with connection.cursor() as cursor:
                cursor.execute(CLEANUP_FIXED_SUCCESS_SQL)
                row = _exact_mapping(
                    cursor.fetchone(),
                    expected_columns=_CLEANUP_RESULT_COLUMNS,
                    operation="cleanup",
                )
            cleaned = row["cleaned"]
            if type(cleaned) is not bool:
                raise ADTOFWorkerSmokeDatabaseProtocolError("Smoke database cleanup result is invalid.")
            if cleaned:
                connection.commit()
            else:
                connection.rollback()
            return cleaned
        except (ADTOFWorkerSmokeContractError, ADTOFWorkerSmokeDatabaseProtocolError):
            _rollback_safely(connection)
            raise
        except Exception as error:
            _rollback_safely(connection)
            raise ADTOFWorkerSmokeDatabaseInfrastructureError(
                "Smoke database cleanup is unavailable."
            ) from error
        finally:
            _close_safely(connection)
