import json
import boto3
import os
from pathlib import Path

def lambda_handler(event, context):
    """
    AWS Lambda function triggered by Amazon EventBridge when an AWS Batch job state changes.
    
    Workflow:
    1. EventBridge detects a Batch Job transitioning to 'SUCCEEDED' or 'FAILED'.
    2. This Lambda parses the event and extracts the 'CONNECTION_ID' environment variable.
    3. It dynamically scans the S3 Output Bucket for the generated Demucs .wav stems.
    4. It generates short-lived Pre-Signed URLs for each stem.
    5. It pushes a JSON payload containing all the URLs directly to the user's browser
       via the API Gateway WebSocket connection.
    """
    s3_client = boto3.client('s3')
    
    # You must configure the WEBSOCKET_ENDPOINT in the Lambda Environment Variables
    # Format: https://{api-id}.execute-api.{region}.amazonaws.com/{stage}
    websocket_endpoint = os.environ.get('WEBSOCKET_ENDPOINT')
    
    if not websocket_endpoint:
        print("Error: Missing WEBSOCKET_ENDPOINT environment variable.")
        return {'statusCode': 500, 'body': 'Configuration error.'}

    # Initialize the specific boto3 client used to communicate with open WebSockets
    apigw_client = boto3.client('apigatewaymanagementapi', endpoint_url=websocket_endpoint)
    
    try:
        # EventBridge passes the complete AWS Batch Job profile in the 'detail' object
        detail = event.get('detail', {})
        status = detail.get('status')
        job_name = detail.get('jobName', 'unknown_job')
        
        # We only care about terminal states (ignore STARTING, RUNNING, etc.)
        if status not in ['SUCCEEDED', 'FAILED']:
            print(f"Job {job_name} is in status {status}. Ignoring.")
            return {'statusCode': 200, 'body': 'Ignored non-terminal state.'}

        # Extract the Environment Variables passed into the Docker container by S3toBatch.py
        env_vars = {}
        container = detail.get('container', {})
        for env in container.get('environment', []):
            env_vars[env['name']] = env['value']
            
        connection_id = env_vars.get('CONNECTION_ID')
        output_bucket = env_vars.get('OUTPUT_BUCKET')
        file_key = env_vars.get('FILE_KEY')
        
        # If no Connection ID was provided, the user may have closed the app or it was triggered manually
        if not connection_id:
            print("No CONNECTION_ID found in job environment. Cannot notify the frontend.")
            return {'statusCode': 200, 'body': 'No connection ID found.'}

        # -----------------------------------------------------
        # Scenario A: The Docker Container Crashed or Failed
        # -----------------------------------------------------
        if status == 'FAILED':
            error_msg = json.dumps({
                "type": "error",
                "message": "Stem splitting job failed on the server."
            })
            apigw_client.post_to_connection(ConnectionId=connection_id, Data=error_msg)
            return {'statusCode': 200, 'body': 'Sent failure notification.'}

        # -----------------------------------------------------
        # Scenario B: The Job Completed Successfully
        # -----------------------------------------------------
        print(f"Job SUCCEEDED. Generating presigned URLs for {file_key}")
        
        # Reconstruct the exact S3 folder where CloudStemSplit.py saved the stems
        # e.g., "stems/1234-uuid-mysong/"
        file_stem = Path(file_key).stem
        prefix = f"stems/{file_stem}/"
        
        # Dynamically list all .wav files generated by Demucs in that folder.
        # This is elegant because it automatically supports 2, 4, or 6 stem modes
        # without us needing to hardcode the track names!
        response = s3_client.list_objects_v2(Bucket=output_bucket, Prefix=prefix)
        
        presigned_urls = {}
        for obj in response.get('Contents', []):
            object_key = obj['Key']
            if object_key.endswith('.wav'):
                # Extract just the filename (e.g., "vocals" or "guitar") as the dictionary key
                track_name = Path(object_key).stem
                
                # Generate a pre-signed GET URL valid for exactly 1 hour (3600 seconds)
                url = s3_client.generate_presigned_url(
                    'get_object',
                    Params={'Bucket': output_bucket, 'Key': object_key},
                    ExpiresIn=3600
                )
                presigned_urls[track_name] = url

        # Construct the final JSON payload for the React frontend
        payload = json.dumps({
            "type": "stems_ready",
            "jobName": job_name,
            "urls": presigned_urls
        })
        
        # Push the payload directly down the WebSocket to the user's specific browser tab!
        print(f"Pushing payload to WebSocket connection: {connection_id}")
        apigw_client.post_to_connection(ConnectionId=connection_id, Data=payload)
        
        return {
            'statusCode': 200,
            'body': json.dumps('Successfully notified frontend.')
        }
        
    except apigw_client.exceptions.GoneException:
        # A GoneException occurs if the user closed their browser tab while the Batch job was running.
        # This is expected behavior.
        print(f"Connection {connection_id} is no longer active. User closed the app.")
        return {'statusCode': 200, 'body': 'Connection gone.'}
    except Exception as e:
        print(f"Error processing EventBridge notification: {e}")
        return {'statusCode': 500, 'body': str(e)}
